export const data = [
    {
        country: 'France',
        artist: 'Марсель Руссо',
        title: 'Охота Амура',
        material: 'Холст, масло (50х80)',
        price: 14500,
        image: "./imagine/France/amur.webp",
        isAtBasket: false,
    },
    { country: 'France',
        artist: 'Анри Селин',
        title: 'Дама с собачкой',
        material: 'Акрил, бумага (50х80)',
        price: 16500,
        image: "./imagine/France/dogmadam.webp",
        isAtBasket: false,
    },
    {
        country: 'France',
        artist: 'Франсуа Дюпон',
        title: 'Процедура',
        material: 'Цветная литография (40х60)',
        price: 20000, 
        image: "./imagine/France/treatment.webp",
        isAtBasket: false,
    },
    {
        country: 'France',
        artist: 'Луи Детуш',
        title: 'Роза',
        material: 'Бумага, акрил (50х80)',
        price: 12000, 
        image: "./imagine/France/rose.webp",
        isAtBasket: false,
    },
    {
        country: 'France',
        artist: 'Франсуа Дюпон',
        title: 'Птичья трапеза',
        material: 'Цветная литография (40х60)',
        price: 22500,
        image: "./imagine/France/birds.webp",
        isAtBasket: false,
    },
    {
        country: 'France',
        artist: 'Пьер Моранж',
        title: 'Пейзаж с рыбой',
        material: 'Цветная литография (40х60)',
        price: 20000,
        image: "./imagine/France/fish.webp",
        isAtBasket: false,
    },
    //   {
    //     country: 'Germany',
    //     artist: 'Курт Вернер',
    //     title: 'Над городом',
    //     material: 'Цветная литография (40х60)',
    //     price: 16000,
    //     image: "./imagine/France/abovecity.webp",
    // },
    //    {
    //     country: 'Germany',
    //     artist: 'Макс Рихтер',
    //     title: 'Птенцы',
    //     material: 'Холст, масло (50х80)',
    //     price: 14500,
    //     image: "./imagine/France/nestlings.webp",
    // },
    //     {
    //     country: 'Germany',
    //     artist: 'Мартин Майер',
    //     title: 'Среди листьев',
    //     material: 'Цветная литография (40х60)',
    //     price: 20000,
    //     image: "./imagine/France/leaf.webp",
    // },
    //     {
    //     country: 'Germany',
    //     artist: 'Герман Беккер',
    //     title: 'Яркая птица',
    //     material: 'Цветная литография (40х60)',
    //     price: 13000,
    //     image: "./imagine/France/colorfulbird.webp",
    // },
    //     {
    //     country: 'Germany',
    //     artist: 'Вульф Бауэр',
    //     title: 'Дятлы',
    //     material: 'Бумага, акрил (50х80)',
    //     price: 20000,
    //     image: "./imagine/France/woodpeckers.webp",
    // },
    //     {
    //     country: 'Germany',
    //     artist: 'Вальтер Хартманн',
    //     title: 'Большие воды',
    //     material: 'Бумага, акрил (50х80)',
    //     price: 23000,
    //     image: "./imagine/France/water.webp",
    // },
    //      {
    //     country: 'England',
    //     artist: 'Пол Смит',
    //     title: 'Дикий зверь',
    //     material: 'Акварель, бумага (50х80)',
    //     price: 19500,
    //     image: "./imagine/France/moose.webp",
    // },
//         {
//         country: 'England',
//         artist: 'Джон Уайт',
//         title: 'Скалистый берег',
//         material: 'Цветная литография (40х60)',
//         price: 17500,
//         image: "./imagine/France/cliffs.webp",
//     },
//         {
//         country: 'England',
//         artist: 'Джим Уотсон',
//         title: 'Река и горы',
//         material: 'Акварель, бумага (50х80)',
//         price: 20500,
//         image: "./imagine/France/river.webp",
//     },
//   {
//         country: 'England',
//         artist: 'Юджин Зиллион',
//         title: 'Белый попугай',
//         material: 'Цветная литография (40х60)',
//         price: 15500,
//         image: "./imagine/France/parrot.webp",
//     },
    // {
    //     country: 'England',
    //     artist: 'Эрик Гиллман',
    //     title: 'Ночная рыба',
    //     material: 'Акварель, бумага (50х80)',
    //     price: 12500,
    //     image: "./imagine/France/nightfish.webp",
    // },
    //   {
    //     country: 'England',
    //     artist: 'Альфред Барр',
    //     title: 'Рыжий кот',
    //     material: 'Цветная литография (40х60)',
    //     price: 21000,
    //     image: "./imagine/France/cat.webp",
    // },

];